[tool.poetry]
name = "pelican-md-include"
version = "0.0.0"
description = "Pelican plugin for using Markdown-Include extension"
authors = ["Rafael Laboissière <rafael@laboissiere.net>"]
license = "AGPL-3.0"
readme = "README.md"
keywords = ["pelican", "plugin"]
repository = "https://github.com/pelican-plugins/md-include"
documentation = "https://docs.getpelican.com"
packages = [
    { include = "pelican" },
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Framework :: Pelican",
    "Framework :: Pelican :: Plugins",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.urls]
"Funding" = "https://donate.getpelican.com/"
"Issue Tracker" = "https://github.com/pelican-plugins/md-include/issues"

[tool.poetry.dependencies]
python = "^3.6"
pelican = "^4.5"
markdown = {version = "^3.2.2", optional = true}

[tool.poetry.dev-dependencies]
black = "^22.8.0"
flake8 = "^3.9.0"
flake8-black = "^0.2.1"
invoke = "^1.5.0"
isort = "^5.7.0"
livereload = "^2.6.3"
markdown = "^3.3.4"
markdown-include = "^0.7.0"
pytest = "^7.1.3"
pytest-cov = "^2.11.1"
pytest-pythonpath = "^0.7.3"
pytest-sugar = "^0.9.4"
Werkzeug = "^1.0.1"

[tool.poetry.extras]
markdown = ["markdown"]

[tool.autopub]
project-name = "Use Markdown-Include extension"
git-username = "botpub"
git-email = "botpub@autopub.rocks"
append-github-contributor = true

[tool.isort]
# Maintain compatibility with Black
profile = "black"
multi_line_output = 3

# Sort imports within their section independent of the import type
force_sort_within_sections = true

# Designate "pelican" as separate import section
known_pelican = "pelican"
sections = "FUTURE,STDLIB,THIRDPARTY,PELICAN,FIRSTPARTY,LOCALFOLDER"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
